add_newline = false

format = '''
 [$directory ]()[λ ](bold bright-green)
'''

[directory]
format = '[$path]($style)'
style = 'bright-purple'
truncation_length = 1

[python]
style = 'bold yellow'
format = '[ $version $virtualenv ]($style)'

[git_branch]
format = '[$branch(:$remote_branch) ]($style)'
style = 'bold green'
