add_newline = false

format = '''
 [$directory ]()[❭](bold white)[❭](bold green)[❭ ](bold bright-green)[$python]()[$git_branch]()[$git_status]()
'''

[directory]
format = '[$path]($style)'
style = 'bright-purple'
truncation_length = 1

[python]
style = 'bold yellow'
format = '[ $version $virtualenv]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'bold green'
