add_newline = false

format = '''
 [$directory ]()[❭](bold white)[❭](bold green)[❭](bold bright-green)[ $python ]()
'''

[directory]
format = '[$path]($style)'
style = 'bright-purple'
truncation_length = 1

[python]
style = 'bold yellow'
format = '[ $version $virtualenv]($style)'